# Generated by Django 6.0.4 on 2026-04-23 03:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('ONLINE', 'Online'), ('SOLO', 'Play vs Yourself'), ('BOT', 'Play vs Bot')], default='ONLINE', max_length=10)),
                ('bot_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('current_fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for Player'), ('IN_PROGRESS', 'In Progress'), ('CHECKMATE', 'Checkmate'), ('STALEMATE', 'Stalemate'), ('DRAW', 'Draw'), ('RESIGNED', 'Resigned')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_move_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('from_square', models.CharField(max_length=2)),
                ('to_square', models.CharField(max_length=2)),
                ('piece_moved', models.CharField(max_length=20)),
                ('piece_captured', models.CharField(blank=True, default='', max_length=20)),
                ('promotion', models.CharField(blank=True, default='', max_length=10)),
                ('notation', models.CharField(blank=True, default='', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_check', models.BooleanField(default=False)),
                ('is_checkmate', models.BooleanField(default=False)),
                ('is_stalemate', models.BooleanField(default=False)),
                ('fen_after_move', models.CharField(blank=True, max_length=100, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=500)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchmakingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('min_rating', models.IntegerField(default=0)),
                ('max_rating', models.IntegerField(default=3000)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_status', to='game.player')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='player_black',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_black', to='game.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_white',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_white', to='game.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='game.player'),
        ),
    ]
