# Generated by Django 6.0.4 on 2026-04-15 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('ONLINE', 'Онлайн'), ('SOLO', 'С самим собой'), ('BOT', 'Против бота')], default='ONLINE', max_length=10)),
                ('player_white', models.CharField(blank=True, default='', max_length=100)),
                ('player_black', models.CharField(blank=True, default='', max_length=100)),
                ('current_fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100)),
                ('status', models.CharField(choices=[('WAITING', 'Ожидание игрока'), ('IN_PROGRESS', 'В процессе'), ('CHECKMATE', 'Мат'), ('STALEMATE', 'Пат'), ('DRAW', 'Ничья'), ('RESIGNED', 'Сдача')], default='WAITING', max_length=20)),
                ('winner', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_move_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('from_square', models.CharField(max_length=2)),
                ('to_square', models.CharField(max_length=2)),
                ('piece_moved', models.CharField(max_length=20)),
                ('piece_captured', models.CharField(blank=True, default='', max_length=20)),
                ('promotion', models.CharField(blank=True, default='', max_length=10)),
                ('notation', models.CharField(blank=True, default='', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_check', models.BooleanField(default=False)),
                ('is_checkmate', models.BooleanField(default=False)),
                ('is_stalemate', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.game')),
            ],
        ),
    ]
