# Generated by Django 6.0.4 on 2026-04-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_time_remaining',
            field=models.FloatField(default=900),
        ),
        migrations.AddField(
            model_name='game',
            name='time_control',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='game',
            name='white_time_remaining',
            field=models.FloatField(default=900),
        ),
    ]
