# Generated by Django 6.0.4 on 2026-04-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('SOLO', 'Play vs Yourself'), ('BOT', 'Play vs Bot')], default='ONLINE', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for Player'), ('IN_PROGRESS', 'In Progress'), ('CHECKMATE', 'Checkmate'), ('STALEMATE', 'Stalemate'), ('DRAW', 'Draw'), ('RESIGNED', 'Resigned')], default='WAITING', max_length=20),
        ),
    ]
