# Generated by Django 6.0.4 on 2026-04-22 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmakingqueue',
            name='is_active',
        ),
        migrations.AddField(
            model_name='matchmakingqueue',
            name='max_rating',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='matchmakingqueue',
            name='min_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchmakingqueue',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_status', to='game.player'),
        ),
    ]
