# Generated by Django 6.0.4 on 2026-04-22 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_matchmakingqueue_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bot_level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
