# Generated by Django 6.0.4 on 2026-04-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_bot_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='fen_after_move',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
